FROM python:3.9-slim

WORKDIR /app

# Update all packages
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Configure the correct command to start the flask application
CMD [ "python", "app.py" ]